Bot経由でゲームサーバのステータスを確認したい
botan-party/hansel pull request #10
Opened 2020-12-19 10:05 UTC by Sut103

## 関連するチケット
* #3 

## やったこと
## みること

2020-12-21 14:40 UTC, shokkunrf requested changes
動作確認OK
命名について気になった箇所があったので、そこの変更をしてもらえればApproveです

2020-12-21 14:40 UTC, shokkunrf commented on config/config.go
> +	GetStatusMessage        string
`StartTriggerMessage`, `HibernateTriggerMessage`に命名を合わせたほうがいいと思う。
`GetStatusTriggerMessage`にするか、StartとHibernateから`Trigger`を取るかしたい。他でもOK。

2020-12-21 15:56 UTC, Sut103 commented on config/config.go
> +	GetStatusMessage        string
前者の`FooTriggerMessage`に統一しました: fb6be44

2020-12-22 10:27 UTC, shokkunrf approved these changes
👍

2020-12-22 10:57 UTC, merged